jwt:
  key: "YourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHere"
  access-token-expiration: 10
  refresh-token-expiration: 30
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  application:
    name: MSTxFleet-Auth
MONGO_SERVICE_URL: localhost:8888/MSTXFLEET-DBS-MONGODB

logging:
  level:
    feign: DEBUG
    org.springframework.data.rest: DEBUG